language: php
php:
  - '7.0'

install:
  - composer install

notifications:
  email:
    recipients:
      - DavidNineRoc@gmail.com
    on_success: never
    on_failure: always
script:
  - vendor/bin/phpunit